name: Hide Sensitive Information
on: push
jobs:
  print-secret-token:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        run: echo "adding tokens"
        env:
          TEST_TOKEN: ${{ secrets.TEST_SECRET }}
      - name: Add Mask
        run: echo "::add-mask::${{ secrets.TEST_SECRET }}"
      - name: Echo a secret
        run: echo "your secret token is ${{ secrets.TEST_SECRET }}"
